sonar.projectKey=simple-apps
sonar.sources=.

sonar.host.url=http://172.23.6.115:9000
sonar.login=sqp_ff07670cacb04e622385377219be294fb0b5f3ce

# 🔥 INI YANG PALING PENTING
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# optional (biar clean)
sonar.exclusions=node_modules/**,coverage/**